### ISSUE TITLE
fitted values and Stan

### ISSUE THREAD

**Issue by ASKurz** [andrewheiss/bayesf22-notebook#1]
Hey @andrewheiss, your `bayesf22-notebook` is one of the resources I'm using to learn how to use Stan (**rstan** specifically, in my case). In [Section 9.3](https://bayesf22-notebook.classes.andrewheiss.com/bayes-rules/09-chapter.html#run-the-model), you used a `transformed parameters` block to define a series of `mu` values, and later in [Section 9.4](https://bayesf22-notebook.classes.andrewheiss.com/bayes-rules/09-chapter.html#interpreting-the-posterior) you commented how there's no `add_linpred_draws()` method for Stan models. This lines up with my experience that other convenience function like `fitted()` do not apply to Stan models. Is it correct to say that the `mu[i]` values that resulted from your `transformed parameters`  are the same as what one might call "fitted" values, and if so, would you say that this is the preferred way to compute fitted values?

```
transformed parameters {
  vector[n] mu;
  mu = beta0 + beta1 * X;
}
```

**Comment by andrewheiss** [comment]
Yeah, that's what I've seen—calculating the `mu` or `pi` or whatever the linear predictor part of the model is inside a `transformed parameters` block or a `generated quantities` block (like in [Section 13.6](https://bayesf22-notebook.classes.andrewheiss.com/bayes-rules/13-chapter.html#extending-the-model) where I have `vector[n] pi_hat = alpha + X * beta;` for a logit model) is the standard way to re-create what {brms} and {tidybayes} do with `fitted()`

**Comment by ASKurz** [comment]
For fitted values, do you see any advantage to using `transformed parameters` versus `generated quantities`?

**Comment by andrewheiss** [comment]
I think it's supposed to happen in `generated quantities`. Things that are made in `transformed parameters` are designed to be used elsewhere, like in sampling or in modeling, while stuff made in `generated quantities` tend to be post-estimation things.

The [Stan manual has this](https://mc-stan.org/docs/2_18/reference-manual/program-block-generated-quantities.html):

> It is more efficient to define a variable in the generated quantities block instead of the transformed parameters block. Therefore, if a quantity does not play a role in the model, it should be defined in the generated quantities block.

(I have it in `transformed parameters` in section 9 here because I didn't fully know what I was doing)

**Comment by ASKurz** [comment]
"...because I didn't fully know what I was doing"--I relate to this so hard I feel it in my bones. Thanks for your thoughts, Andrew!
